services:
    app:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: auth99-backend
        tty: true
        ports:
          - "8000:8000"
        volumes:
          - .:/src
