services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth99-backend
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/src

  mysql:
    image: mysql:latest
    platform: linux/amd64
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth99
      TZ: "Asia/Tokyo"
    volumes:
      - .db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
